### ISSUE TITLE
Error: read ECONNRESET parse file and insert node

### ISSUE THREAD

**Issue by imtase** [philippkueng/node-neo4j#43]
Hello,

I have a file with 32 000 lines and I want to use each one for create a node (use the insertNode function but I have same problem when I change by Cypher method. With small files I have no problem but when have a lot of line I have an error :

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:904:11)
    at TCP.onread (net.js:558:19)

For load and read the file I use fast-csv

Thanks for your help.

**Comment by stormit-vn** [comment]
We cannot go-live without getting this issue fixed. So does anyone has a resolution can fix this issue?

**Comment by philippkueng** [comment]
@stormit-vn hi, sorry to hear that you're still struggling with this. I no longer work with neo4j on a daily basis but am wondering if it's related to how many connections your host OS allows to be made to the database. In case you're doing a batch import, have you tried using https://caolan.github.io/async/docs.html#queue and specifying a count of workers so that neo4j can keep up with it?

If this doesn't solve or point you in the right direction can you elaborate on your use-case? and if possible share a piece of code that reproduces the problem.

**Comment by stormit-vn** [comment]
@philippkueng Phi it just a few connections and it just CRUD operations, sometimes we got read error and sometimes we got write error.

However, I just updated our code to specify some configurations when opening a new connection, until now I didn't receive any error likes. Here is the configuration I am using

```javascript
{
                encrypted: false,
                // The maximum total number of connections allowed to be managed by the connection pool, per host.
                // This includes both in-use and idle connections. No maximum connection pool size is imposed
                // by default.
                maxConnectionPoolSize: 100,
                // The maximum allowed lifetime for a pooled connection in milliseconds. Pooled connections older than this
                // threshold will be closed and removed from the pool. Such discarding happens during connection acquisition
                // so that new session is never backed by an old connection. Setting this option to a low value will cause
                // a high connection churn and might result in a performance hit. It is recommended to set maximum lifetime
                // to a slightly smaller value than the one configured in network equipment (load balancer, proxy, firewall,
                // etc. can also limit maximum connection lifetime). No maximum lifetime limit is imposed by default. Zero
                // and negative values result in lifetime not being checked.
                maxConnectionLifetime: 0,
                // The maximum amount of time to wait to acquire a connection from the pool (to either create a new
                // connection or borrow an existing one.
                connectionAcquisitionTimeout: 60000,

                // Specify the maximum time in milliseconds transactions are allowed to retry via
                // <code>Session#readTransaction()</code> and <code>Session#writeTransaction()</code> functions.
                // These functions will retry the given unit of work on `ServiceUnavailable`, `SessionExpired` and transient
                // errors with exponential back-off using initial delay of 1 second.
                // Default value is 30000 which is 30 seconds.
                maxTransactionRetryTime: 60000,

                // Provide an alternative load balancing strategy for the routing driver to use.
                // Driver uses "least_connected" by default.
                // <b>Note:</b> We are experimenting with different strategies. This could be removed in the next minor
                // version.
                // loadBalancingStrategy: 'least_connected' | 'round_robin',

                // Specify socket connection timeout in milliseconds. Numeric values are expected. Negative and zero values
                // result in no timeout being applied. Connection establishment will be then bound by the timeout configured
                // on the operating system level. Default value is 5000, which is 5 seconds.
                connectionTimeout: 30000
            }
```

**Comment by philippkueng** [comment]
@stormit-vn I believe you've got your answer with https://github.com/neo4j/neo4j-javascript-driver/issues/126#issuecomment-430609055 - while the library you're using is using bolt, I believe neo4j does respond the same way for HTTP requests too if it kills connections. Will try to replicate it later. Thanks for connecting the issues and bringing it to our attention.
