### ISSUE TITLE
simple insert not working on GrapheneDB 

### ISSUE THREAD

**Issue by pranavpunjabi** [philippkueng/node-neo4j#60]
I tried this simple insert sample using node-neo4j driver with db hosted on GrapheneDB.

``` javascript
var neo4j = require('node-neo4j');

db = new neo4j('http://user:password@ompdb.sb05.stations.graphenedb.com:24789');

db.insertNode({
    name: 'Darth Vader',
    sex: 'male'
},function(err, node){
    if(err) throw err;

    console.log(node.data);

    console.log(node._id);
});
```

The program fails to execute and gives out an error: 

Error: Response body is empty
    at /home/pranavpunjabi/node_modules/node-neo4j/lib/main.js:52:15
    at Request.callback (/home/pranavpunjabi/node_modules/node-neo4j/node_modules/superagent/lib/node/index.js:748:3)
    at Request.<anonymous> (/home/pranavpunjabi/node_modules/node-neo4j/node_modules/superagent/lib/node/index.js:135:10)
    at Request.emit (events.js:109:17)
    at IncomingMessage.<anonymous> (/home/pranavpunjabi/node_modules/node-neo4j/node_modules/superagent/lib/node/index.js:938:12)
    at IncomingMessage.emit (events.js:131:20)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:358:11)

Am I using this driver correctly?

**Comment by philippkueng** [comment]
thanks @pranavpunjabi for letting us know, i'll look into it over lunch today. Sorry about that.

**Comment by joemaffei** [comment]
Oddly, this is the only driver so far that has been working for me -- on Graphene or locally.

**Comment by noamyogev84** [comment]
I'm not able to get a connection to grapheneDB as well.
any progress with this issue?
